/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as RoleSelectRouteImport } from './routes/role-select'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedCitizenRouteImport } from './routes/_authenticated/citizen'
import { Route as AuthenticatedBenefitsRouteImport } from './routes/_authenticated/benefits'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedSchemesIdRouteImport } from './routes/_authenticated/schemes.$id'
import { Route as AuthenticatedPartnerIntakeRouteImport } from './routes/_authenticated/partner.intake'
import { Route as AuthenticatedPartnerCitizensRouteImport } from './routes/_authenticated/partner.citizens'
import { Route as AuthenticatedPartnerCitizensIdRouteImport } from './routes/_authenticated/partner.citizens.$id'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectRoute = RoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCitizenRoute = AuthenticatedCitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenefitsRoute = AuthenticatedBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchemesIdRoute = AuthenticatedSchemesIdRouteImport.update({
  id: '/schemes/$id',
  path: '/schemes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerIntakeRoute =
  AuthenticatedPartnerIntakeRouteImport.update({
    id: '/intake',
    path: '/intake',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerCitizensRoute =
  AuthenticatedPartnerCitizensRouteImport.update({
    id: '/citizens',
    path: '/citizens',
    getParentRoute: () => AuthenticatedPartnerRoute,
  } as any)
const AuthenticatedPartnerCitizensIdRoute =
  AuthenticatedPartnerCitizensIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPartnerCitizensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role-select': typeof RoleSelectRoute
  '/stories': typeof StoriesRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/partner/citizens': typeof AuthenticatedPartnerCitizensRouteWithChildren
  '/partner/intake': typeof AuthenticatedPartnerIntakeRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
  '/partner/citizens/$id': typeof AuthenticatedPartnerCitizensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/role-select': typeof RoleSelectRoute
  '/stories': typeof StoriesRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/benefits': typeof AuthenticatedBenefitsRoute
  '/citizen': typeof AuthenticatedCitizenRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/partner/citizens': typeof AuthenticatedPartnerCitizensRouteWithChildren
  '/partner/intake': typeof AuthenticatedPartnerIntakeRoute
  '/schemes/$id': typeof AuthenticatedSchemesIdRoute
  '/partner/citizens/$id': typeof AuthenticatedPartnerCitizensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/role-select': typeof RoleSelectRoute
  '/stories': typeof StoriesRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/benefits': typeof AuthenticatedBenefitsRoute
  '/_authenticated/citizen': typeof AuthenticatedCitizenRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/partner/citizens': typeof AuthenticatedPartnerCitizensRouteWithChildren
  '/_authenticated/partner/intake': typeof AuthenticatedPartnerIntakeRoute
  '/_authenticated/schemes/$id': typeof AuthenticatedSchemesIdRoute
  '/_authenticated/partner/citizens/$id': typeof AuthenticatedPartnerCitizensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/role-select'
    | '/stories'
    | '/applications'
    | '/assistant'
    | '/benefits'
    | '/citizen'
    | '/documents'
    | '/family'
    | '/partner'
    | '/profile'
    | '/api/stt'
    | '/api/tts'
    | '/partner/citizens'
    | '/partner/intake'
    | '/schemes/$id'
    | '/partner/citizens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/role-select'
    | '/stories'
    | '/applications'
    | '/assistant'
    | '/benefits'
    | '/citizen'
    | '/documents'
    | '/family'
    | '/partner'
    | '/profile'
    | '/api/stt'
    | '/api/tts'
    | '/partner/citizens'
    | '/partner/intake'
    | '/schemes/$id'
    | '/partner/citizens/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/role-select'
    | '/stories'
    | '/_authenticated/applications'
    | '/_authenticated/assistant'
    | '/_authenticated/benefits'
    | '/_authenticated/citizen'
    | '/_authenticated/documents'
    | '/_authenticated/family'
    | '/_authenticated/partner'
    | '/_authenticated/profile'
    | '/api/stt'
    | '/api/tts'
    | '/_authenticated/partner/citizens'
    | '/_authenticated/partner/intake'
    | '/_authenticated/schemes/$id'
    | '/_authenticated/partner/citizens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RoleSelectRoute: typeof RoleSelectRoute
  StoriesRoute: typeof StoriesRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-select': {
      id: '/role-select'
      path: '/role-select'
      fullPath: '/role-select'
      preLoaderRoute: typeof RoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/citizen': {
      id: '/_authenticated/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof AuthenticatedCitizenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benefits': {
      id: '/_authenticated/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof AuthenticatedBenefitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schemes/$id': {
      id: '/_authenticated/schemes/$id'
      path: '/schemes/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof AuthenticatedSchemesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/intake': {
      id: '/_authenticated/partner/intake'
      path: '/intake'
      fullPath: '/partner/intake'
      preLoaderRoute: typeof AuthenticatedPartnerIntakeRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/citizens': {
      id: '/_authenticated/partner/citizens'
      path: '/citizens'
      fullPath: '/partner/citizens'
      preLoaderRoute: typeof AuthenticatedPartnerCitizensRouteImport
      parentRoute: typeof AuthenticatedPartnerRoute
    }
    '/_authenticated/partner/citizens/$id': {
      id: '/_authenticated/partner/citizens/$id'
      path: '/$id'
      fullPath: '/partner/citizens/$id'
      preLoaderRoute: typeof AuthenticatedPartnerCitizensIdRouteImport
      parentRoute: typeof AuthenticatedPartnerCitizensRoute
    }
  }
}

interface AuthenticatedPartnerCitizensRouteChildren {
  AuthenticatedPartnerCitizensIdRoute: typeof AuthenticatedPartnerCitizensIdRoute
}

const AuthenticatedPartnerCitizensRouteChildren: AuthenticatedPartnerCitizensRouteChildren =
  {
    AuthenticatedPartnerCitizensIdRoute: AuthenticatedPartnerCitizensIdRoute,
  }

const AuthenticatedPartnerCitizensRouteWithChildren =
  AuthenticatedPartnerCitizensRoute._addFileChildren(
    AuthenticatedPartnerCitizensRouteChildren,
  )

interface AuthenticatedPartnerRouteChildren {
  AuthenticatedPartnerCitizensRoute: typeof AuthenticatedPartnerCitizensRouteWithChildren
  AuthenticatedPartnerIntakeRoute: typeof AuthenticatedPartnerIntakeRoute
}

const AuthenticatedPartnerRouteChildren: AuthenticatedPartnerRouteChildren = {
  AuthenticatedPartnerCitizensRoute:
    AuthenticatedPartnerCitizensRouteWithChildren,
  AuthenticatedPartnerIntakeRoute: AuthenticatedPartnerIntakeRoute,
}

const AuthenticatedPartnerRouteWithChildren =
  AuthenticatedPartnerRoute._addFileChildren(AuthenticatedPartnerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBenefitsRoute: typeof AuthenticatedBenefitsRoute
  AuthenticatedCitizenRoute: typeof AuthenticatedCitizenRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesIdRoute: typeof AuthenticatedSchemesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBenefitsRoute: AuthenticatedBenefitsRoute,
  AuthenticatedCitizenRoute: AuthenticatedCitizenRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesIdRoute: AuthenticatedSchemesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RoleSelectRoute: RoleSelectRoute,
  StoriesRoute: StoriesRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
